import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { locales } from '@/i18n/config';
import EnContent, { frontmatter as enFrontmatter } from './en.mdx';
import ZhContent, { frontmatter as zhFrontmatter } from './zh.mdx';
import DeContent, { frontmatter as deFrontmatter } from './de.mdx';

/**
 * Per-route wrapper — auto-generated by
 * scripts/docs-migration/generate-page-wrappers.mjs.
 *
 * Picks the locale-specific MDX at render time. If a translation is
 * missing the EN fallback is served (zh.mdx / de.mdx for API pages
 * are EN copies until translations land — see migrate.mjs §applyFallback).
 *
 * Path: src/app/[locale]/docs/api/policies/validate
 */
type Props = {
  params: Promise<{ locale: string }>;
};

/**
 * Static export — Phase 1 docs subtree is repo-owned content. Combined
 * with `generateStaticParams` below, Next.js prerenders one HTML/RSC
 * file per (locale × route) at build time. Cloudflare Workers serve
 * directly from CDN edge with no per-request CPU.
 */
export const dynamic = 'force-static';

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const FRONTMATTER: Record<string, { title?: string; description?: string }> = {
  en: enFrontmatter ?? {},
  zh: zhFrontmatter ?? {},
  de: deFrontmatter ?? {},
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const fm = FRONTMATTER[locale] ?? FRONTMATTER.en;
  return {
    title: fm.title ? `${fm.title} · Aster Cloud Docs` : 'Aster Cloud Docs',
    description: fm.description,
  };
}

export default async function Page({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);
  if (locale === 'zh') return <ZhContent />;
  if (locale === 'de') return <DeContent />;
  if (locale === 'en') return <EnContent />;
  notFound();
}
