import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import EnContent, { frontmatter as enFrontmatter } from './en.mdx';
import ZhContent, { frontmatter as zhFrontmatter } from './zh.mdx';
import DeContent, { frontmatter as deFrontmatter } from './de.mdx';

/**
 * Per-route wrapper — auto-generated by
 * scripts/docs-migration/generate-page-wrappers.mjs.
 *
 * Picks the locale-specific MDX at render time. If a translation is
 * missing the EN fallback is served (zh.mdx / de.mdx for API pages
 * are EN copies until translations land — see migrate.mjs §applyFallback).
 *
 * Path: src/app/[locale]/docs/getting-started/quickstart
 */
const SITE_URL = 'https://aster-lang.cloud';
const ROUTE_SLUG = '/docs/getting-started/quickstart';

type Props = {
  params: Promise<{ locale: string }>;
};

const FRONTMATTER: Record<string, { title?: string; description?: string }> = {
  en: enFrontmatter ?? {},
  zh: zhFrontmatter ?? {},
  de: deFrontmatter ?? {},
};

function localizedDocsUrl(locale: string): string {
  const prefix = locale === 'en' ? '' : `/${locale}`;
  return `${SITE_URL}${prefix}${ROUTE_SLUG}`;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const fm = FRONTMATTER[locale] ?? FRONTMATTER.en;
  const canonical = localizedDocsUrl(locale);
  return {
    title: fm.title ? `${fm.title} · Aster Cloud Docs` : 'Aster Cloud Docs',
    description: fm.description,
    alternates: {
      canonical,
      languages: {
        en: localizedDocsUrl('en'),
        zh: localizedDocsUrl('zh'),
        de: localizedDocsUrl('de'),
        'x-default': localizedDocsUrl('en'),
      },
    },
  };
}

export default async function Page({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);
  if (locale === 'zh') return <ZhContent />;
  if (locale === 'de') return <DeContent />;
  if (locale === 'en') return <EnContent />;
  notFound();
}
